<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="1" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="75811" started-at="2020-01-17T18:15:36Z" finished-at="2020-01-17T18:16:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="75811" started-at="2020-01-17T18:15:36Z" finished-at="2020-01-17T18:16:52Z">
      <class name="com.qa.Guru99Bank.Tests.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="setUp" is-config="true" duration-ms="17726" started-at="2020-01-17T18:15:36Z" finished-at="2020-01-17T18:15:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getLoginPageTitleTest()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="getLoginPageTitleTest" duration-ms="329" started-at="2020-01-17T18:15:54Z" finished-at="2020-01-17T18:15:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Page is correct expected [HubSpotLogin] but found [HubSpot Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Page is correct expected [HubSpotLogin] but found [HubSpot Login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.qa.Guru99Bank.Tests.LoginTest.getLoginPageTitleTest(LoginTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLoginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="tearDown" is-config="true" duration-ms="588" started-at="2020-01-17T18:15:54Z" finished-at="2020-01-17T18:15:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="setUp" is-config="true" duration-ms="12512" started-at="2020-01-17T18:15:55Z" finished-at="2020-01-17T18:16:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getLoginPageTitleTest()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="getLoginPageTitleTest" duration-ms="125" started-at="2020-01-17T18:16:08Z" finished-at="2020-01-17T18:16:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Page is correct expected [HubSpotLogin] but found [HubSpot Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Page is correct expected [HubSpotLogin] but found [HubSpot Login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.qa.Guru99Bank.Tests.LoginTest.getLoginPageTitleTest(LoginTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLoginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="tearDown" is-config="true" duration-ms="250" started-at="2020-01-17T18:16:08Z" finished-at="2020-01-17T18:16:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="setUp" is-config="true" duration-ms="12357" started-at="2020-01-17T18:16:08Z" finished-at="2020-01-17T18:16:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getLoginPageTitleTest()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="getLoginPageTitleTest" duration-ms="3003" started-at="2020-01-17T18:16:20Z" finished-at="2020-01-17T18:16:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Page is correct expected [HubSpotLogin] but found [HubSpot Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Page is correct expected [HubSpotLogin] but found [HubSpot Login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.qa.Guru99Bank.Tests.LoginTest.getLoginPageTitleTest(LoginTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLoginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="tearDown" is-config="true" duration-ms="299" started-at="2020-01-17T18:16:23Z" finished-at="2020-01-17T18:16:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="setUp" is-config="true" duration-ms="12317" started-at="2020-01-17T18:16:24Z" finished-at="2020-01-17T18:16:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getLoginPageTitleTest()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="getLoginPageTitleTest" duration-ms="3362" started-at="2020-01-17T18:16:36Z" finished-at="2020-01-17T18:16:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Page is correct expected [HubSpotLogin] but found [HubSpot Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Page is correct expected [HubSpotLogin] but found [HubSpot Login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.qa.Guru99Bank.Tests.LoginTest.getLoginPageTitleTest(LoginTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLoginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="tearDown" is-config="true" duration-ms="214" started-at="2020-01-17T18:16:39Z" finished-at="2020-01-17T18:16:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="setUp" is-config="true" duration-ms="12257" started-at="2020-01-17T18:16:40Z" finished-at="2020-01-17T18:16:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getLoginPageTitleTest()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="getLoginPageTitleTest" duration-ms="42" started-at="2020-01-17T18:16:52Z" finished-at="2020-01-17T18:16:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Page is correct expected [HubSpotLogin] but found [HubSpot Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Page is correct expected [HubSpotLogin] but found [HubSpot Login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.qa.Guru99Bank.Tests.LoginTest.getLoginPageTitleTest(LoginTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLoginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.Guru99Bank.Tests.LoginTest@604ed9f0]" name="tearDown" is-config="true" duration-ms="293" started-at="2020-01-17T18:16:52Z" finished-at="2020-01-17T18:16:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.Guru99Bank.Tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
